# Generated by Django 4.1.7 on 2023-06-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('son', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('come_code', models.CharField(max_length=5)),
                ('ad_code', models.CharField(max_length=3)),
            ],
        ),
    ]
