# Generated by Django 4.1.7 on 2023-06-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('son', '0002_commune'),
    ]

    operations = [
        migrations.CreateModel(
            name='function1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_f1', models.CharField(max_length=15)),
                ('montant_f1', models.FloatField()),
                ('ad_code_f1', models.CharField(max_length=3)),
            ],
        ),
    ]
