# Generated by Django 4.1.7 on 2023-07-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('son', '0003_function1'),
    ]

    operations = [
        migrations.CreateModel(
            name='function2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_f2', models.CharField(max_length=15)),
                ('montant_f2', models.FloatField()),
                ('Nb_Fact', models.IntegerField()),
                ('ad_code_f2', models.CharField(max_length=3)),
            ],
        ),
    ]
