# Generated by Django 4.1.7 on 2023-07-03 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('son', '0005_function3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='function3',
            old_name='ad_code_f2',
            new_name='ad_code_f3',
        ),
    ]
